updated ubuntu.install

diff --git a/cloud/ubuntu.install b/cloud/ubuntu.install
--- a/cloud/ubuntu.install
+++ b/cloud/ubuntu.install
@@ -12,24 +12,30 @@ if [[ "x${EUID}" != "x0" ]]; then
 fi
 
 printf "${CYAN}Configuring VPN secrets${NC}\n"
-read -p 'PPTP username: ' USER_NAME
+FILE=/opt/config.json
+if [[ ! -f "$FILE" ]]; then
+  read -p 'PPTP username: ' USER_NAME
 
-if [[ "x${USER_NAME}" = "x" ]]; then
-  printf "${RED}Error: username is empty${NC}\n"
-  exit 1
+  if [[ "x${USER_NAME}" = "x" ]]; then
+    printf "${RED}Error: username is empty${NC}\n"
+    exit 1
+  fi
+
+  read -s -p 'PPTP password: ' USER_PASSWORD
+
+  if [[ "x${USER_PASSWORD}" = "x" ]]; then
+    printf  "${RED}Error: password is empty${NC}\n"
+    exit 1
+  fi
+
+  echo "{\"users\":{\"${USER_NAME}\":{\"password\":\"${USER_PASSWORD}\",\"ip\":\"192.168.122.10\",\"forwarding\":[{\"sourceIp\":\"192.168.8.46\",\"sourcePort\":\"8080\",\"destinationPort\":7894}],\"routing\":[{\"route\":\"192.168.8.0/24\"}]}}}" >/opt/config.json
+  chown -R $(whoami):$(whoami) /opt/config.json
+
+  printf "${GREEN}PPTP secret created${NC}\n"
+else
+  printf "${GREEN}PPTP secret exists${NC}\n"
 fi
 
-read -s -p 'PPTP password: ' USER_PASSWORD
-
-if [[ "x${USER_PASSWORD}" = "x" ]]; then
-  printf  "${RED}Error: password is empty${NC}\n"
-  exit 1
-fi
-
-echo "{\"users\":{\"${USER_NAME}\":{\"password\":\"${USER_PASSWORD}\",\"ip\":\"192.168.122.10\",\"forwarding\":[{\"sourceIp\":\"192.168.8.46\",\"sourcePort\":\"8080\",\"destinationPort\":7894}],\"routing\":[{\"route\":\"192.168.8.0/24\"}]}}}" >/opt/config.json
-chown -R $(whoami):$(whoami) /opt/config.json
-
-printf "${GREEN}PPTP secret created${NC}\n"
 
 printf "${CYAN}Starting installing Docker${NC}\n"
 apt-get update && sudo apt-get install -y iptables git iptables-persistent
@@ -60,6 +66,6 @@ docker stop remote-ctrl
 docker rm remote-ctrl
 docker image prune -a -f
 set -e
-docker run -d --name=remote-ctrl -p 1723:1723 -p 7894:7894 -v /opt/ppp/chap-secrets:/etc/ppp/chap-secrets --privileged --restart=always vassio/pptp-port-forwarding:latest
+docker run -d --name=remote-ctrl -p 1723:1723 -p 7894:7894 -v /opt/config.json:/opt/config.json --privileged --restart=always vassio/pptp-port-forwarding:latest
 printf "${CYAN}Rebooting${NC}\n"
 reboot
