updated install script

diff --git a/cloud/ubuntu.install b/cloud/ubuntu.install
--- a/cloud/ubuntu.install
+++ b/cloud/ubuntu.install
@@ -44,12 +44,14 @@ if [[ ! -f "$SMARTTHINGS_FILE" ]]; then
   read -p "Do you need Smartthings integration [y/n]? " -n 1 -r
   echo
   if [[ $REPLY =~ ^[Yy]$ ]]
-  then
-      FILE=/opt/remote-ctrl-gsm.json
-      if [[ ! -f "$FILE" ]]; then
-          echo '{"port":8099,"portUI":8080,"smartthings":{"devices":[]},"smartapp":["https://graph.api.smartthings.com","https://graph-na02-useast1.api.smartthings.com","https://graph-na04-useast2.api.smartthings.com","https://graph-eu01-euwest1.api.smartthings.com","https://graph-ap02-apnortheast2.api.smartthings.com"],"users":[{"id":"0","username":"admin","password":"admin"}],"connectionType":"local"}'>/opt/remote-ctrl-gsm.json
-      fi
-      export SMARTTHINGS_PAGE=' -p 8080:8080 -p 8099:8099 -v /opt/remote-ctrl-gsm.json:/opt/config/remote-ctrl-gsm.json '
+    then
+      read -p 'Smartthings Admin password: ' ADMIN_PASSWORD
+        if [[ "x${ADMIN_PASSWORD}" = "x" ]]; then
+          printf "${RED}Error: admin password is empty${NC}\n"
+          exit 1
+    fi
+    echo '{"port":8099,"portUI":8080,"smartthings":{"devices":[]},"smartapp":["https://graph.api.smartthings.com","https://graph-na02-useast1.api.smartthings.com","https://graph-na04-useast2.api.smartthings.com","https://graph-eu01-euwest1.api.smartthings.com","https://graph-ap02-apnortheast2.api.smartthings.com"],"users":[{"id":"0","username":"admin","password":"'"${ADMIN_PASSWORD}"'"}],"connectionType":"local"}' >/opt/remote-ctrl-gsm.json
+    export SMARTTHINGS_PAGE=' -p 8080:8080 -p 8099:8099 -v /opt/remote-ctrl-gsm.json:/opt/config/remote-ctrl-gsm.json '
   fi
   printf "${GREEN}Smartthings integration configured${NC}\n"
 else
